name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - name: Setup Nodejs environment
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run tests
      - run: npm ci
      - run: npm test
